server:
  address: localhost
  port: 8080
#JPA
spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/test
#      username: root
#      password: 4788
    datasource:
      driver-class-name: com.mongodb.jdbc.MongoDriver
      username: root
      password: 4788
      hikari:
        jdbc-url: jdbc:mongodb://localhost:27017/test
    main:
      allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR